// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package trengin

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStrategy is an autogenerated mock type for the Strategy type
type MockStrategy struct {
	mock.Mock
}

// Actions provides a mock function with given fields:
func (_m *MockStrategy) Actions() Actions {
	ret := _m.Called()

	var r0 Actions
	if rf, ok := ret.Get(0).(func() Actions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Actions)
		}
	}

	return r0
}

// Run provides a mock function with given fields: ctx
func (_m *MockStrategy) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewMockStrategyT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStrategy creates a new instance of MockStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStrategy(t NewMockStrategyT) *MockStrategy {
	mock := &MockStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
